import java.util.Scanner;
public class Main
{
   public static void main(String[] args)
   {
      int row, y, z, number = 1;
      Scanner sc = new Scanner(System.in);
      System.out.println("Enter the number of rows you want to print: ");
      row = sc.nextInt();
      System.out.println("Output: ");
      for(y = 1; y <= row; y++)
      {
         for(z = 1; z <= y; z++)
         {
            System.out.print(number + " ");
            number++;
         }
         System.out.println();
      }
      sc.close();
   }
}
